version: '3'

services:
  database:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - ~/database/data-scraper:/data/db
  # api:
  #   image: kunooo/marketplace-orderbook:20211210.1
  #   volumes:
  #     - ./appsettings/appsettings.json:/workdir/appsettings/appsettings.json
  #     - ./secrets/secrets.json:/workdir/secrets/secrets.json
  #   ports:
  #     - 8080:8080
  #   # depends_on:
  #   #   - postgres
  api:
    image: kunooo/transfer-producer:20220127.1
    env_file:
      - .env
    ports:
      - 8080:8080
    # depends_on:
    #   - postgres

# mongodb://mongo:mongo@localhost:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false